name: github pages

on:
  push:
    branches:
      - sources

jobs:
  deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.4
        with:
          node-version: '12.x'

      - run: npm install -g yarn # Extra Step

      - name: Cache
        uses: actions/cache@v2.1.3
        with:
          path: ~/.npm
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - run: yarn install --frozen-lockfile
      # - run: npm run format
      # - run: npm run test
      - run: yarn build

      - name: GH Pages deploy
        uses: Cecilapp/GitHub-Pages-deploy@3.1.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          email: zogacc@gmail.com
          build_dir: public  # optional
          branch: master   # optional